### ISSUE TITLE
iconv is deprecated

### ISSUE THREAD

**Issue by lencioni** [noeticpenguin/soap4r-noeticpenguin#8]
I am seeing the following warning:

```
vendor/rails/activesupport/lib/active_support/dependencies.rb:253:in `block in require': iconv will be deprecated in the future, use String#encode instead.
```

After adding some basic logging, I was able to trace this back to:

```
soap4r-ruby1.9-2.0.5/lib/xsd/iconvcharset.rb:9:in `<top (required)>'
```

Converting this to use `String#encode` instead of `iconv` would  help futureproof the gem while making our consoles a little cleaner.

**Comment by futhr** [comment]
+1
